In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Lecture 6

## Table Review: Welcome Survey

In [2]:
welcome = Table.read_table('welcome_survey_sp22.csv')
welcome.show(5)

In [3]:
# On average, how long do side-sleepers sleep?
side_sleepers = welcome.where('Sleep position', are.containing('side'))
np.average(side_sleepers.column('Hours of sleep'))

7.1131167268351385

In [4]:
# How many students get at least 8 hours of sleep each night (on average)?
# First way: Query of Values that meet a criteria
welcome.where('Hours of sleep', are.above_or_equal_to(8)).num_rows

473

In [5]:
# Use the column() method to get an array of the result of the condition below
welcome.column('Hours of sleep') >= 8

array([ True, False,  True, ..., False, False, False], dtype=bool)

In [6]:
# Second way: The number of values that are not zero
np.count_nonzero(welcome.column('Hours of sleep') >= 8)

473

In [7]:
# Third way: Adding the values in the array
np.sum(welcome.column('Hours of sleep') >= 8)

473

In [8]:
# Create a table with only the two sleep-related columns, 
# with names 'Hours' and 'Position'
two_col = welcome.select('Hours of sleep', 'Sleep position')
sleep = two_col.relabeled(0, 'Hours').relabeled(1, 'Position')
sleep.show(3)

In [9]:
# Second way
two_col = welcome.drop(
    'Handedness', 'Extraversion',
    'Pant leg', 'Number of textees',
    'Pets', 'Piercings',
    'Year', 'Extroversion')
sleep = two_col.relabeled(0, 'Hours').relabeled(1, 'Position')
sleep.show(3)

## Discussion Question: NBA Salaries

The table nba has columns player, position, and salary.
<ol type = "a">
<li> Create a table containing the records of all point guards (PG) who made more than $15M </li>
<li> From the new table take out the value that is common to all of the records.</li>
<li> Reflect: After evaluating these two expressions in order, what's the final result? </li>
</ol>

In [10]:
nba = Table.read_table('nba_salaries.csv')
nba.show(3)

In [11]:
# Question (1) Create a table containing the records of all point guards (PG) who made more than $15M
guards = ...
guards.show(3)

AttributeError: 'ellipsis' object has no attribute 'show'

In [12]:
# Question (2) From the new table take out the value that is common to all of the records.
guards = ...
guards.show(3)

AttributeError: 'ellipsis' object has no attribute 'show'

### Question (3) Reflect: After evaluating these two expressions in order, what's the final result?

Reflect here

## Census ##
Creating a census: The process of collecting data about

Understanding the column variables:<br>
* SEX
* AGE

Problems with the census data collection:

In [13]:
full = Table.read_table('nc-est2019-agesex-res.csv')
full

SEX  | AGE  | CENSUS2010POP | ESTIMATESBASE2010 | POPESTIMATE2010 | POPESTIMATE2011 | POPESTIMATE2012 | POPESTIMATE2013 | POPESTIMATE2014 | POPESTIMATE2015 | POPESTIMATE2016 | POPESTIMATE2017 | POPESTIMATE2018 | POPESTIMATE2019
0    | 0    | 3944153       | 3944160           | 3951430         | 3963092         | 3926570         | 3931258         | 3954787         | 3983981         | 3954773         | 3893990         | 3815343         | 3783052
0    | 1    | 3978070       | 3978090           | 3957730         | 3966225         | 3977549         | 3942698         | 3948891         | 3973133         | 4002903         | 3972711         | 3908830         | 3829599
0    | 2    | 4096929       | 4096939           | 4090621         | 3970654         | 3978925         | 3991740         | 3958711         | 3966321         | 3991349         | 4020045         | 3987032         | 3922044
0    | 3    | 4119040       | 4119051           | 4111688         | 4101644         | 3981531         | 3991017         | 4005928         | 3974351         | 3982984         | 4006946         | 4033038         | 3998665
0    | 4    | 4063170       | 4063186           | 4077346         | 4121488         | 4111490         | 3992502         | 4004032         | 4020292         | 3989750         | 3997280         | 4018719         | 4043323
0    | 5    | 4056858       | 4056872           | 4064521         | 4087054         | 4131049         | 4121876         | 4004576         | 4017589         | 4035033         | 4003452         | 4008443         | 4028281
0    | 6    | 4066381       | 4066412           | 4072904         | 4074531         | 4096631         | 4141126         | 4133372         | 4017388         | 4031568         | 4048018         | 4014057         | 4017227
0    | 7    | 4030579       | 4030594           | 4042990         | 4082821         | 4084175         | 4106756         | 4152666         | 4145872         | 4030888         | 4044139         | 4058370         | 4022319
0    | 8    | 4046486       | 4046497           | 4025501         | 4052773         | 4092559         | 4094513         | 4118349         | 4165033         | 4158848         | 4042924         | 4054236         | 4066194
0    | 9    | 4148353       | 4148369           | 4125312         | 4035319         | 4062726         | 4103052         | 4106068         | 4130887         | 4177895         | 4170813         | 4053179         | 4061874
... (296 rows omitted)

In [14]:
partial = full.select('SEX', 'AGE', 'POPESTIMATE2014', 'POPESTIMATE2019')
partial.show(5)

In [15]:
us_pop = partial.relabeled(2, '2014').relabeled(3, '2019')
us_pop.show(5)

In [16]:
# From the newly created table, find the records for the ages over 100.

### Percent Change ###

The amount of increase or decrease relative to the initial value.</br>
$Change = \dfrac{}{}*100$

In [17]:
# Percent Change in Population for 2014 vs 2019
us_pop.with_column(
    '% Diff', ( us_pop.column('2019') - us_pop.column('2014') ) / us_pop.column('2014')
).set_format('% Diff', PercentFormatter)

SEX  | AGE  | 2014    | 2019    | % Diff
0    | 0    | 3954787 | 3783052 | -4.34%
0    | 1    | 3948891 | 3829599 | -3.02%
0    | 2    | 3958711 | 3922044 | -0.93%
0    | 3    | 4005928 | 3998665 | -0.18%
0    | 4    | 4004032 | 4043323 | 0.98%
0    | 5    | 4004576 | 4028281 | 0.59%
0    | 6    | 4133372 | 4017227 | -2.81%
0    | 7    | 4152666 | 4022319 | -3.14%
0    | 8    | 4118349 | 4066194 | -1.27%
0    | 9    | 4106068 | 4061874 | -1.08%
... (296 rows omitted)

### 2019 Sex Ratios ###

Ratio: 

Proportion:

In [18]:
us_pop_2019 = us_pop.drop('2014')
us_pop_2019.show(3)

In [28]:
# Create a table from the newly created table that only displays the age category for the entire population.
all_ages = us_pop_2019.drop('2014')
all_ages

SEX  | AGE  | 2019
0    | 0    | 3783052
0    | 1    | 3829599
0    | 2    | 3922044
0    | 3    | 3998665
0    | 4    | 4043323
0    | 5    | 4028281
0    | 6    | 4017227
0    | 7    | 4022319
0    | 8    | 4066194
0    | 9    | 4061874
... (296 rows omitted)

In [20]:
#Add a proportion column to easily see which gender has more
pop_2019 = all_ages.column('2019').item(0)
all_ages.with_column(
    'Proportion', all_ages.column('2019')/pop_2019
).set_format('Proportion', PercentFormatter)

AttributeError: 'ellipsis' object has no attribute 'column'

In [21]:
preteen = us_pop_2019.where('AGE', are.between(10, 13))
preteen

SEX  | AGE  | 2019
0    | 10   | 4060940
0    | 11   | 4189261
0    | 12   | 4208387
1    | 10   | 2071778
1    | 11   | 2138037
1    | 12   | 2149819
2    | 10   | 1989162
2    | 11   | 2051224
2    | 12   | 2058568

In [22]:
# Write a table that contains all of the females from the 2019 table.
females_all_rows = ...

# Write a new table from the table you just created that does only includes valid ages.
females = ...
females.show(3)

AttributeError: 'ellipsis' object has no attribute 'show'

In [23]:
# Write a table that contains all of the males from the 2019 table for all valid ages.
# Tip: Edit the code for the female table
males_all_rows = ...
males = ...
males.show(3)

AttributeError: 'ellipsis' object has no attribute 'show'

#### Based on the tables above, what questions do you have?

### $F:M$ Ratios ###
$F:M$ means

Statistically, we know that women outlive men. Let's explore that.

* If $F = M$ then
* If $F > M$ then
* If $F < M$ then

In [24]:
f_to_m_ratios = females.column(2) / males.column(2)

ratios = Table().with_columns(
    'Age', females.column('AGE'),
    'F:M Ratio', f_to_m_ratios
)

AttributeError: 'ellipsis' object has no attribute 'column'

In [25]:
ratios.sort('Age', descending=False)

NameError: name 'ratios' is not defined

#### What do you notice? What questions does that bring up?


#### What are your hypotheses?

In [26]:
ratios.sort('Age').take(np.arange(, ))

SyntaxError: invalid syntax (2894966027.py, line 1)

## Line Plot
Displaying data in an easy to read format.

In [27]:
ratios.plot('Age', 'F:M Ratio')

NameError: name 'ratios' is not defined

#### What do you notice about the scale of the axes in the line plot? ####

In [ ]:
ratios.plot('Age', 'F:M Ratio')
plots.ylim(0, 100) # Sets y-axis from 0 to 100
plots.show()

#### What do you notice when the x- and y-axis are the same scale?

#### What questions or observations can be made about this data after looking at the two graphs? List as many as you can think of?